-- AlterTable
ALTER TABLE `products` MODIFY `warranty` VARCHAR(191) NULL,
    MODIFY `product_description` VARCHAR(191) NULL,
    MODIFY `product_price` VARCHAR(191) NULL,
    MODIFY `discounted_price` INTEGER NULL,
    MODIFY `product_images` VARCHAR(191) NULL,
    MODIFY `image` VARCHAR(191) NULL,
    MODIFY `offer` VARCHAR(191) NULL,
    MODIFY `bought` VARCHAR(191) NULL,
    MODIFY `rating` INTEGER NULL,
    MODIFY `frame_width` VARCHAR(191) NULL,
    MODIFY `temple_length` VARCHAR(191) NULL,
    MODIFY `lens_height` VARCHAR(191) NULL,
    MODIFY `coupon_code` VARCHAR(191) NULL,
    MODIFY `coupon_amount` BIGINT NULL,
    MODIFY `stokke` INTEGER NULL,
    MODIFY `product_url` VARCHAR(191) NULL,
    MODIFY `seo_title` VARCHAR(191) NULL,
    MODIFY `keyword` VARCHAR(191) NULL,
    MODIFY `created_on` DATETIME(3) NULL,
    MODIFY `updated_on` DATETIME(3) NULL,
    MODIFY `products_categories_id` VARCHAR(191) NULL,
    MODIFY `products_brand_id` INTEGER NULL,
    MODIFY `status` INTEGER NULL;
